CONNECTION_URL=jdbc:mysql://localhost:3306/biblioteca?noAccessToProcedureBodies=true
LOGIN_USER=login
LOGIN_PASS=login
AMMINISTRATORE_USER=amministratore
AMMINISTRATORE_PASS=amministratore
BIBLIOTECARIO_USER=bibliotecario
BIBLIOTECARIO_PASS=bibliotecario
RESPONSABILE_USER=responsabile
RESPONSABILE_PASS=responsabile